// src/texts/challengeNumbers.ts
export const challengeNumberInterpretations: {
  [key: number]: { title: string; description: string }
} = {
  0: { title: "Desafio", description: "O Aprendizado de Todos os Números. O 0 é o número da totalidade, que contém dentro de si todas as energias. Quando aparece como desafio, significa que você escolheu passar por todos os aprendizados da vida, vivendo experiências ligadas a cada um dos números de 1 a 9. É como se cada ciclo fosse um novo teste, trazendo oportunidades de crescimento e desenvolvimento em diferentes áreas. O grande propósito do 0 é a empatia. Por viver tantas situações distintas, você aprende na prática a compreender profundamente o outro, suas dores, suas alegrias e seus processos. Essa vivência múltipla desperta em você uma sabedoria única: você pode ajudar pessoas em diferentes contextos, porque sempre terá algo semelhante que já experimentou e que pode compartilhar." },
  1: { title: "Desafio", description: "O seu desafio é aprender a lidar com o excesso e a falta da energia do 1. Quando está em excesso, você pode se tornar arrogante, autoritário ou agressivo, acreditando que só a sua verdade importa. Pode cair no egoísmo e no individualismo, afastando pessoas e se isolando. Em contrapartida, quando a energia do 1 está em falta, surge a insegurança, a baixa autoestima e a dificuldade de acreditar em si mesmo. Nesses momentos, você pode se sentir incapaz de agir, paralisado diante da vida ou sempre dependendo da opinião dos outros. O equilíbrio está em viver a liderança com autoridade verdadeira: saber se colocar com firmeza, assumir seu espaço e confiar no seu poder pessoal, mas sem deixar que isso se transforme em imposição ou violência." },
  2: { title: "Desafio", description: "O seu desafio é não se perder ao cuidar dos outros. Quando a energia do 2 está em excesso, você pode se anular, abrindo mão das próprias necessidades para não desagradar, vivendo dependência emocional e dificuldade em se impor. Já quando essa energia falta, pode se tornar impaciente, intolerante ou frio, rejeitando parcerias e preferindo se fechar. O aprendizado do 2 é equilibrar a generosidade com a firmeza interior: aprender a ser paciente e colaborativo, mas sem perder de vista a própria identidade. Você está aqui para viver a diplomacia e a escuta verdadeira, oferecendo cuidado e presença, mas lembrando sempre que também merece ser cuidado." },
  3: { title: "Desafio", description: "O seu desafio é cuidar dos excessos e da falta de expressão. Quando a energia do 3 está em excesso, você pode falar demais, se tornar tagarela e agir com impulsividade verbal, dizendo coisas das quais depois se arrepende. Pode se dispersar em muitas ideias ao mesmo tempo, sem conseguir concluir nada, ou buscar apenas prazer imediato, deixando de lado a disciplina necessária para concretizar seus sonhos. O 3 em excesso também pode trazer um lado imaturo, em que mesmo adultos tendem a se comportar de forma infantilizada, evitando responsabilidades. Já quando essa energia falta, surge a timidez, a insegurança e a dificuldade de se expressar, o que gera frustração. O grande aprendizado do 3 é usar a comunicação e a criatividade com consciência: encontrar equilíbrio entre leveza e responsabilidade, maturidade e espontaneidade." },
  4: { title: "Desafio", description: "O seu desafio é cuidar para não cair na rigidez e no excesso de controle. Quando a energia do 4 está em excesso, você pode se tornar controlador, inflexível e teimoso, querendo que tudo siga apenas o seu método. O medo e a insegurança também fazem parte desse aprendizado: você pode buscar tanta estabilidade que acaba se fechando para o novo, paralisado diante de mudanças que poderiam trazer crescimento. Essa necessidade exagerada de segurança pode impedir a expansão da sua vida. Já quando a energia do 4 falta, surge a desorganização, a instabilidade e a dificuldade de manter o foco, o que atrapalha seus resultados. O grande aprendizado do 4 é equilibrar disciplina com flexibilidade, mantendo a dedicação e a persistência sem deixar que o medo paralise." },
  5: { title: "Desafio", description: "O seu desafio é equilibrar a busca por liberdade com a responsabilidade. Quando a energia do 5 está em excesso, você pode se tornar ansioso, agitado, rebelde e até irresponsável, sempre em busca de novidade sem concluir o que começou. A impulsividade pode levar a escolhas apressadas ou arrependimentos. Já quando essa energia falta, surgem o medo e a insegurança, que podem te paralisar e te prender a uma rotina que sufoca, tirando a sua coragem natural de se aventurar. O aprendizado do 5 é não permitir que o medo te feche, mas também não usar a liberdade como fuga. Você está aqui para viver como explorador da vida, uma pessoa do mundo, que encontra vitalidade em cada movimento, coragem em cada mudança e sabedoria em cada experiência." },
  6: { title: "Desafio", description: "O seu desafio é equilibrar o amor ao outro com o amor por si mesmo. Quando a energia do 6 está em excesso, você pode se apegar demais, viver com ciúmes, carregar compromissos que não são seus ou se anular para agradar. Por ser muito sensível, às vezes você pode se fechar, e isso acaba gerando frieza e afastamento das pessoas. Há também o risco da preguiça e da zona de conforto: você pode se acostumar tanto com a estabilidade que evita se movimentar e acaba deixando de crescer. Além disso, em busca de paz e harmonia, você pode acabar engolindo muitas coisas para não gerar conflitos, internalizando sentimentos e acumulando peso dentro de si." },
  7: { title: "Desafio", description: "O seu desafio é equilibrar a busca pela perfeição com a leveza de viver. Quando a energia do 7 está em excesso, você pode se tornar crítico demais, exigente, isolado ou cético, fechando-se na mente e se afastando das pessoas. Muitas vezes, pode ter dificuldade em aceitar críticas, por ser extremamente exigente consigo mesmo. A autocrítica pode se tornar pesada, levando à autopunição e a uma sensação constante de nunca ser suficiente. Já quando essa energia falta, você pode viver na superficialidade, sem disciplina para estudar ou se aprofundar, o que gera frustração. O aprendizado do 7 é não deixar que o perfeccionismo e a rigidez paralisem o seu crescimento." },
  8: { title: "Desafio", description: "O seu desafio é cuidar para não se afastar dos seus valores. Quando a energia do 8 está em excesso, pode surgir a mentira, a desonestidade, a falsidade ou escolhas por caminhos errados que ferem a ética. Você também pode cair na armadilha de remoer situações, ser muito severo e duro consigo mesmo. Outro ponto é a forma de se comunicar: frieza nas palavras ou grosseria podem ferir quem está ao seu lado. Existe ainda o risco de viver os extremos com o dinheiro de um lado, o materialismo e a ganância; do outro, a falta de valorização do dinheiro e dos recursos que possui. Já quando essa energia falta, pode surgir a insegurança e a sensação de impotência diante das responsabilidades." },
  9: { title: "Desafio", description: "O seu desafio é ser mais prático, menos idealista, mais focado e menos dispersivo. Quando a energia do 9 está em excesso, você pode se perder em sonhos e ideais, sem conseguir concretizar suas visões no mundo real. Pode também se sobrecarregar tentando ajudar a todos, esquecendo de cuidar de si mesmo. Já quando essa energia falta, você pode se tornar egoísta, fechado ao sofrimento alheio e desconectado da sua missão de servir. O aprendizado do 9 é encontrar equilíbrio entre o amor universal e a praticidade, entre servir aos outros e cuidar de si mesmo." },
  11: { title: "Desafio", description: "O seu desafio é equilibrar a sensibilidade espiritual com a vida prática. Quando a energia do 11/2 está em excesso, você pode se tornar hipersensível, absorvendo energias negativas dos outros e se sentindo sobrecarregado emocionalmente. Pode também se perder em idealismos espirituais sem conseguir aplicá-los na vida real. Já quando essa energia falta, você pode se desconectar da sua intuição e dos seus dons espirituais, vivendo apenas no plano material. O aprendizado do 11/2 é usar seus dons espirituais para servir, mas sem se esquecer de manter os pés no chão e cuidar das suas necessidades humanas básicas." },
  22: { title: "Desafio", description: "O seu desafio é equilibrar a grandiosidade da visão com a humildade da execução. Quando a energia do 22/4 está em excesso, você pode se tornar megalomaníaco, achando que só você pode realizar grandes feitos, ou pode se perder em projetos grandiosos sem conseguir concretizá-los. Pode também usar seus dons de forma egoísta, visando apenas o próprio benefício. Já quando essa energia falta, você pode subestimar seu potencial e se contentar com realizações menores do que é capaz. O aprendizado do 22/4 é usar sua visão e capacidade de realização para servir ao coletivo, mantendo sempre a humildade e a disciplina necessárias para transformar sonhos em realidade." },
};

export default challengeNumberInterpretations;
