export const soulCompatibility: Record<string, { harmony: string; challenge: string }> = {
  "1-1": { harmony: "Ambos líderes independentes que respeitam as ambições um do outro", challenge: "Disputas de poder podem surgir; aprendam a compartilhar o protagonismo" },
  "1-2": { harmony: "Líder e apoiador criam dinâmica equilibrada", challenge: "Dominância do 1 pode sobrecarregar a sensibilidade do 2" },
  "1-3": { harmony: "Energia criativa encontra ação ousada", challenge: "Seriedade do 1 conflita com a alegria do 3" },
  "1-4": { harmony: "Visão encontra execução prática", challenge: "Riscos do 1 conflitam com cautela do 4" },
  "1-5": { harmony: "Aventura e liberdade alimentam ambos os espíritos", challenge: "Ambos resistem ao compromisso e rotina" },
  "1-6": { harmony: "Liderança equilibrada por cuidado amoroso", challenge: "Independência do 1 vs necessidade de união do 6" },
  "1-7": { harmony: "Ação encontra sabedoria em união poderosa", challenge: "Extroversão do 1 vs necessidade de solidão do 7" },
  "1-8": { harmony: "Casal poderoso com potencial massivo", challenge: "Naturezas competitivas podem criar conflito" },
  "1-9": { harmony: "Pioneiro encontra humanitário para o bem maior", challenge: "Foco próprio do 1 vs amor universal do 9" },
  "2-2": { harmony: "Profunda compreensão emocional e harmonia", challenge: "Ambos podem evitar conflitos e decisões difíceis" },
  "2-3": { harmony: "Apoio gentil encontra expressão alegre", challenge: "Sensibilidade do 2 ferida pela abordagem casual do 3" },
  "2-4": { harmony: "Estabilidade e devoção criam base sólida", challenge: "Ambos resistem a mudanças e novas experiências" },
  "2-5": { harmony: "Alma gentil aprende com espírito livre", challenge: "Inquietação do 5 perturba necessidade de segurança do 2" },
  "2-6": { harmony: "Cuidadores naturais criam santuário amoroso", challenge: "Ambos podem se tornar codependentes" },
  "2-7": { harmony: "Intuição encontra análise belamente", challenge: "Necessidade de proximidade do 2 vs solidão do 7" },
  "2-8": { harmony: "Parceiro apoiador ajuda realizador a ter sucesso", challenge: "Intensidade do 8 sobrecarrega gentileza do 2" },
  "2-9": { harmony: "Almas compassivas se unem em serviço", challenge: "Ambos dão demais, negligenciam autocuidado" },
  "3-3": { harmony: "Alegria dupla, criatividade e diversão social", challenge: "Falta de base e foco prático" },
  "3-4": { harmony: "Criatividade fundamentada por sabedoria prática", challenge: "Espontaneidade do 3 vs necessidade de estrutura do 4" },
  "3-5": { harmony: "Aventura e diversão criam vínculo emocionante", challenge: "Ambos evitam responsabilidade e compromisso" },
  "3-6": { harmony: "Expressão criativa em lar amoroso", challenge: "Natureza social do 3 vs foco doméstico do 6" },
  "3-7": { harmony: "Alma artística encontra mente filosófica", challenge: "Extroversão do 3 vs introspecção do 7" },
  "3-8": { harmony: "Talento criativo encontra perspicácia nos negócios", challenge: "Seriedade do 8 diminui alegria do 3" },
  "3-9": { harmony: "Expressão criativa serve a humanidade", challenge: "Ambos dispersam energia em muitos projetos" },
  "4-4": { harmony: "Estabilidade sólida como rocha e confiança mútua", challenge: "Rigidez e resistência ao crescimento" },
  "4-5": { harmony: "Estabilidade encontra aventura em equilíbrio", challenge: "Diferenças fundamentais nas necessidades de estilo de vida" },
  "4-6": { harmony: "Construindo belo lar estável juntos", challenge: "Ambos teimosos em seus caminhos" },
  "4-7": { harmony: "Sabedoria prática encontra profundidade espiritual", challenge: "Materialismo do 4 vs espiritualidade do 7" },
  "4-8": { harmony: "Construindo império com base sólida", challenge: "Tendências workaholicas negligenciam relacionamento" },
  "4-9": { harmony: "Serviço prático à humanidade", challenge: "Foco do 4 em detalhes vs visão ampla do 9" },
  "5-5": { harmony: "Aventureiros amantes da liberdade exploram juntos", challenge: "Sem âncora ou estabilidade no relacionamento" },
  "5-6": { harmony: "Liberdade equilibrada por compromisso amoroso", challenge: "Desejo de viajar do 5 vs necessidades domésticas do 6" },
  "5-7": { harmony: "Aventuras intelectuais e conversas profundas", challenge: "Ambos precisam de extenso espaço pessoal" },
  "5-8": { harmony: "Energia dinâmica cria empreendimentos emocionantes", challenge: "Caos do 5 vs necessidade de controle do 8" },
  "5-9": { harmony: "Aventuras mundanas servem bem maior", challenge: "Ambos resistem a se estabelecer" },
  "6-6": { harmony: "Parceria profundamente amorosa e nutritiva", challenge: "Martírio e excesso de responsabilidade" },
  "6-7": { harmony: "Amor encontra sabedoria em união sagrada", challenge: "Necessidade de proximidade do 6 vs solidão do 7" },
  "6-8": { harmony: "Lar nutritivo encontra sucesso material", challenge: "Necessidades emocionais do 6 vs foco no trabalho do 8" },
  "6-9": { harmony: "Serviço e amor pela família e mundo", challenge: "Ambos negligenciam próprias necessidades pelos outros" },
  "7-7": { harmony: "Vínculo espiritual e intelectual profundo", challenge: "Muito isolamento do mundo e um do outro" },
  "7-8": { harmony: "Sabedoria guia manifestação poderosa", challenge: "Espiritualidade do 7 vs materialismo do 8" },
  "7-9": { harmony: "Buscadores espirituais em jornada compartilhada", challenge: "Ambos desapegados da realidade prática" },
  "8-8": { harmony: "Casal poderoso alcançando sucesso massivo", challenge: "Competição e batalhas de controle" },
  "8-9": { harmony: "Sucesso material serve objetivos humanitários", challenge: "Ambição do 8 vs altruísmo do 9" },
  "9-9": { harmony: "Almas compassivas servindo a humanidade", challenge: "Ambos dão tudo, negligenciam necessidades práticas" },
};

export const relationshipTypes = {
  romantic: "Parceria Romântica",
  business: "Parceria de Negócios",
  friendship: "Amizade",
};
