export const destinyNumberInterpretations: {
  [key: number]: { title: string; description: string }
} = {
  0: { title: "Caminho de Destino", description: "Você carrega um destino especial e único, com um caminho que se manifesta de forma singular na sua jornada de vida." },
  1: { title: "Caminho de Destino", description: "Você veio para liderar, inovar e abrir caminhos. \n\nO número 1 no destino revela que sua vida é guiada pelo impulso de começar, criar e ser pioneiro. \n\nVocê carrega a energia da iniciativa, da coragem e da originalidade, e por isso a vida sempre te convida a assumir posições de destaque e independência. \n\nO seu propósito é se tornar referência, mostrando às pessoas que é possível construir algo do zero e transformar ideias em realidade. \n\nA vibração do 1 traz também a força da superação: você sempre será chamado a confiar em si, acreditar nas suas escolhas e não se deixar abalar pelas opiniões externas. \n\nA sua missão é liderar com confiança, abrir novas trilhas e deixar sua marca no mundo." },
  2: { title: "Caminho de Destino", description: "Você veio para unir e para viver em parceria. \n\nO 2 no destino mostra que sua missão é aprender a dividir a vida com os outros, construindo relações de cooperação e confiança.\n\n A vida vai sempre te convidar a cultivar a generosidade, a escuta e o acolhimento, porque você tem a sensibilidade de perceber o que o outro sente e precisa. \n\nSeu propósito é desenvolver paciência, flexibilidade e diplomacia, tornando-se alguém capaz de aproximar pessoas, criar vínculos e favorecer o espírito de grupo. \n\nVocê nasceu para viver a parceria em todos os sentidos, mostrando que quando caminhamos juntos, somos mais fortes." },
  3: { title: "Caminho de Destino", description: "Você veio para se expressar, criar e expandir. \n\nO 3 no destino mostra que sua missão é viver com leveza, alegria e criatividade, usando a comunicação como instrumento para se conectar e inspirar. \n\nVocê nasceu para trazer movimento e cor à vida, aprender a enxergar o belo em cada detalhe e compartilhar isso com os outros. \n\nA vida sempre vai te convidar a se abrir, a se relacionar, a colocar sua voz no mundo, seja por meio da arte, da escrita, da fala ou de qualquer forma criativa de expressão. \n\nO seu propósito é contagiar, levar entusiasmo e estimular o crescimento, mostrando que é possível viver com espontaneidade, prazer e constante amadurecimento." },
  4: { title: "Caminho de Destino", description: "Você veio para construir, organizar e realizar. \n\nO 4 no destino mostra que sua missão é aprender o valor da disciplina, da dedicação e da persistência. \n\nVocê nasceu para criar bases sólidas, dar forma ao que parecia apenas uma ideia e transformar esforço em conquistas reais. \n\nA vida sempre vai te colocar em situações que pedem trabalho focado, responsabilidade e profissionalismo, porque você tem a capacidade de estruturar, planejar e tornar tudo mais estável. \n\nVocê se sente realizado quando percebe que está produzindo e deixando resultados concretos. \n\nO seu propósito é mostrar, pelo exemplo, que o sucesso vem do empenho contínuo e da disciplina bem direcionada." },
  5: { title: "Caminho de Destino", description: "Você veio para viver o movimento, a liberdade e as transformações da vida. \n\nO 5 no destino mostra que sua missão é experimentar, se reinventar e aprender através das mudanças. Você nasceu para ser ousado, dinâmico e corajoso, alguém que precisa sair da rotina, quebrar padrões e se abrir a novas possibilidades. \n\nA vida sempre vai te colocar em situações de movimento, viagens, transições, desafios, contatos com pessoas diferentes — porque você tem dentro de si a energia do explorador. \n\nO seu propósito é viver com vitalidade, inspirar liberdade e mostrar que a coragem de arriscar é a porta para o crescimento. \n\nVocê veio para transformar, mudar e explorar o mundo e viver com liberdade." },
  6: { title: "Caminho de Destino", description: "Você veio para viver o amor, o cuidado e a responsabilidade com as pessoas que fazem parte da sua vida. \n\nO 6 no destino mostra que sua missão é aprender a criar vínculos sólidos, a zelar pela família de origem, pela família que você forma e também pelos amigos que se tornam parte do coração. \n\nVocê carrega em si a energia do conciliador: alguém que veio trazer harmonia, pacificar conflitos e unir pessoas. A vida sempre vai te colocar em situações onde o afeto, o zelo e a dedicação ao outro são fundamentais. \n\nO seu propósito é construir lares, ambientes e relações que transmitam amor, segurança e responsabilidade, vivendo como exemplo de quem se doa, protege e cuida." },
  7: { title: "Caminho de Destino", description: "Você veio para aprender, buscar conhecimento e desenvolver sua espiritualidade. \n\nO 7 no destino mostra que sua missão é investigar, refletir e se aprofundar em si mesmo, cultivando o autoconhecimento como base da sua evolução. \n\nVocê é uma pessoa curiosa, buscadora e analítica, que não se satisfaz com respostas superficiais. \n\nPrecisa de estudo, leitura e momentos de silêncio para encontrar sentido na vida. \n\nO 7 também é o número da perfeição: você gosta de tudo muito bem feito, é detalhista, exigente e valoriza a excelência em tudo o que faz. \n\nO seu propósito é equilibrar razão e espiritualidade, unindo sabedoria intelectual com a conexão interior, e mostrar que o verdadeiro crescimento nasce da consciência e da profundidade." },
  8: { title: "Caminho de Destino", description: "Você vai viver uma vida baseada na verdade, na justiça, na ética e na retidão. \n\nO 8 no destino mostra que sua missão é aprender a lidar com poder e prosperidade de forma responsável e transparente. \n\nVocê é uma pessoa objetiva, que valoriza a clareza e a integridade, e que não tolera injustiças ou incoerências. \n\nA vida vai sempre te colocar diante de situações ligadas ao trabalho, ao dinheiro e à conquista, porque você tem dentro de si a energia da prosperidade. \n\nVocê nasceu para crescer, prosperar e ocupar posições de responsabilidade, mostrando que é possível unir ambição com ética. \n\nO seu propósito é construir uma vida de sucesso e abundância, sem perder os valores que sustentam sua essência." },
  9: { title: "Caminho de Destino", description: "Você veio para viver uma vida de grandes realizações, porque o 9 é o número da materialização e da visão ampla. No destino, ele mostra que você nasceu para ser visionário, enxergar além e transformar ideias em algo concreto que beneficie muitas pessoas. \n\nO seu caminho é profundamente humano: você sente a dor e a alegria do coletivo, e isso te impulsiona a agir. \n\nA vida te chama para usar seu carisma, sua empatia e sua espiritualidade em causas que envolvem serviço, inspiração e contribuição. \n\nVocê tem a capacidade de realizar muito e de deixar um legado que vai além do material, unindo visão, humanidade e amor universal. \n\nO aprendizado do 9 é equilibrar sua missão de servir com a clareza dos seus próprios limites, lembrando que também merece colher frutos daquilo que constrói." },
  11: { title: "Caminho de Destino", description: "Você veio para inspirar e unir. \n\nO 11/2 no destino mostra que sua vida é guiada pela sensibilidade espiritual do 11/2 e pela generosidade acolhedora do 2. \n\nVocê nasceu para ser um canal de luz, reciclar energias e ajudar outras almas, trazendo cura, inspiração e espiritualidade para o mundo. Ao mesmo tempo, carrega a necessidade de viver em parceria: você se fortalece quando está junto do outro, quando compartilha, quando sente que caminha lado a lado. \n\nO seu propósito é integrar espiritualidade e humanidade, inspirando pelo invisível e acolhendo pelo gesto simples, vivendo uma vida de união, compaixão e luz." },
  22: { title: "Caminho de Destino", description: "Você veio para viver a energia da genialidade e da mestria. \n\nO 22/4 no destino mostra que você carrega a força do Mestre Construtor, alguém que nasceu para realizar em grande escala, unir visão e prática, espiritualidade e materialidade. \n\nO 22/4 traz o lado visionário, sonhador e ambicioso, capaz de enxergar o que poucos conseguem e de transformar o impossível em realidade. \n\nÉ também o número da magia: você tem uma sensibilidade espiritual que conecta com as forças da natureza, com a energia dos elementais, com o poder do fogo, das ervas e do invisível. \n\nO 4, por sua vez, dá disciplina, método e estrutura para que tudo isso se materialize. \n\nO seu propósito é transmitir conhecimento, ensinar pelo exemplo da realização e usar seu poder de construir para servir ao coletivo e inspirar o mundo." }

};
