export const dreamNumberInterpretations: {
  [key: number]: { title: string; description: string }
} = {
  1: { title: "Sonho", description: "O seu sonho é vencer, ser reconhecido e conquistar o seu espaço. Você deseja ocupar um lugar de liderança, construir algo que seja só seu e inspirar pessoas pelo seu pioneirismo. O 1 no sonho mostra que você almeja independência total. Seja profissional, financeira ou emocional. Sua fantasia mais profunda é ser dono da sua história, ter liberdade para escolher seu caminho e não depender da aprovação de ninguém. Você deseja provar o seu valor através das suas conquistas e busca constantemente oportunidades para mostrar sua coragem, sua criatividade e sua capacidade de abrir novas portas." },
  2: { title: "Sonho", description: "O seu sonho é viver em parceria verdadeira, rodeado de pessoas que valorizem a cooperação e o cuidado mútuo. Você deseja uma vida em que haja colaboração, delicadeza e um ambiente de grupo saudável, onde cada um possa contribuir e crescer junto. O 2 no sonho revela um profundo desejo de não estar sozinho: você quer dividir a vida, se sentir parte e construir junto com os outros uma base de apoio e confiança." },
  3: { title: "Sonho", description: "O seu sonho é ter uma vida em que possa se expressar plenamente, explorando sua criatividade e vivendo com prazer. Você deseja estar em ambientes que favoreçam o contato social, o movimento e a leveza. Também sonha em viver rodeado de beleza, cultivando o autocuidado e a vaidade saudável que traz bem-estar e autoestima. Quer se sentir livre para experimentar, comunicar e criar, cuidando de si enquanto compartilha sua alegria com o mundo. O 3 no sonho revela o desejo de um cotidiano alegre, dinâmico e cheio de oportunidades para expandir sua energia e crescer como pessoa." },
  4: { title: "Sonho", description: "O seu sonho é alcançar estabilidade e reconhecimento pelo trabalho que realiza. Você deseja construir algo sólido, seja na vida profissional, familiar ou pessoal, e ter a certeza de que sua dedicação será recompensada. O 4 no sonho mostra que você anseia por disciplina, método e estrutura, sonhando com uma vida organizada e equilibrada. O que você mais busca é sentir que está no controle do seu caminho, sendo produtivo e construindo tijolo por tijolo uma base que traga segurança e tranquilidade para o futuro." },
  5: { title: "Sonho", description: "O seu sonho é ter uma vida repleta de liberdade, aventuras e descobertas. Você deseja ser uma pessoa do mundo, estar em movimento, conhecer lugares, pessoas e culturas diferentes. Quer viver experiências que tragam vitalidade, prazer e renovação. O 5 no sonho mostra que você anseia por uma vida sem limitações, com coragem para mudar sempre que sentir necessidade, e com espaço para explorar tanto o mundo exterior quanto o seu próprio interior. O que você mais deseja é viver intensamente, livre de amarras, explorando cada oportunidade como uma nova chance de crescer." },
  6: { title: "Sonho", description: "O seu sonho é viver em harmonia e estar cercado de amor, vínculos verdadeiros e responsabilidades compartilhadas. Você deseja uma família estruturada, um lar acolhedor e relacionamentos cheios de compromisso e confiança. O 6 no sonho mostra que você anseia por proximidade, por um ambiente em que haja cuidado, conciliação e paz. O que você mais deseja é se sentir amado e valorizado, construindo laços que tragam segurança, sensibilidade e pertencimento. Seja na família, no amor ou nas amizades mais íntimas." },
  7: { title: "Sonho", description: "Você adora estudar, adora se conhecer, adora buscar conhecimento e se aprofundar em temas. O seu sonho é ter uma vida de estudo, profundidade e espiritualidade. Você deseja viver em constante desenvolvimento, em um cotidiano que traga espaço para reflexão, autoconhecimento e conexão com a sua fé. O 7 no sonho mostra que você anseia por momentos de introspecção, silêncio e experiências que alimentem sua mente e sua alma. O que você mais deseja é sentir que está crescendo como ser humano, desenvolvendo consciência e vivendo em contato com a verdade." },
  8: { title: "Sonho", description: "O seu sonho é alcançar prosperidade, reconhecimento e independência financeira, mas sempre em uma vida baseada em valores sólidos. Você deseja ocupar cargos importantes, ter sucesso profissional e ser visto como referência de competência e retidão. O 8 no sonho mostra que você anseia por construir uma vida sofisticada, em que possa desfrutar das coisas boas que o dinheiro proporciona, mas sem abrir mão da transparência e da justiça. O que você mais deseja é viver com ambição equilibrada: conquistar muito, mas sempre de forma honesta e com propósito." },
  9: { title: "Sonho", description: "Você sonha em ajudar, em doar e em contribuir com os outros. O 9 no sonho mostra que você atrai naturalmente pessoas que precisam do seu apoio, porque você tem prazer em cuidar e servir. O seu desejo é viver de forma altruísta, ajudando sem esperar nada em troca, seja em grandes causas ou em gestos simples, como um sorriso, um abraço ou uma palavra amiga. Essa atitude é a sua forma de estar no mundo: contribuir para que a vida seja mais leve e mais justa. Você é uma pessoa sensível, intuitiva e capaz de ler os outros com profundidade, e por isso precisa incluir o espiritual na sua vida como fonte de equilíbrio e direção. O que você mais deseja é sentir-se conectado ao coletivo e deixar sua marca de amor no mundo." },
  11: { title: "Sonho", description: "Você sonha em viver uma vida em que espiritualidade e parceria caminham juntas. O 11/2 no sonho mostra que você deseja ser canal de inspiração, ajudar e transformar pessoas, mas também anseia por união, relacionamentos profundos e vínculos de confiança. Você é alguém que se realiza em gestos simples de amor, como um abraço, uma palavra ou um sorriso, e que acredita que a vida ganha mais sentido quando é compartilhada. O seu ideal é viver de forma altruísta, ajudando sem esperar nada em troca, e ao mesmo tempo sentindo-se fortalecido na união com quem escolhe estar ao seu lado." },
  22: { title: "Sonho", description: "Você sonha em realizar grandes coisas, em viver a grandiosidade do 22/4. No fundo, deseja usar sua visão e sua ambição para deixar algo que ultrapasse o tempo, algo que seja duradouro e que marque gerações. Sonha em conquistar o lado material com facilidade, mas não apenas para si: deseja que isso se conecte a um propósito maior, ligado ao espiritual. O 22/4 no sonho também mostra o desejo de ensinar, de transmitir conhecimento e de usar a magia da vida, seja através da espiritualidade, do contato com a natureza ou da intuição refinada para inspirar outras pessoas. O que você mais deseja é que sua vida tenha impacto, tanto no mundo visível quanto no invisível." },
  15: { title: "Sonho", description: "Você sonha em realizar grandes coisas, em viver a grandiosidade do 22/4. No fundo, deseja usar sua visão e sua ambição para deixar algo que ultrapasse o tempo, algo que seja duradouro e que marque gerações. Sonha em conquistar o lado material com facilidade, mas não apenas para si: deseja que isso se conecte a um propósito maior, ligado ao espiritual. O 22/4 no sonho também mostra o desejo de ensinar, de transmitir conhecimento e de usar a magia da vida, seja através da espiritualidade, do contato com a natureza ou da intuição refinada para inspirar outras pessoas. O que você mais deseja é que sua vida tenha impacto, tanto no mundo visível quanto no invisível." }
};

