// src/texts/quarterCycles.ts
// Observação: 4 ciclos (1..4) no ano; o "número do trimestre" (ctNumber) é obtido do cálculo e mapeia para os textos abaixo (1..9).
export const quarterCycleTexts: {
  [key: number | string]: { title: string; description: string }
} = {
  1: { title: "CICLO DO TRIMESTRE 1 – O Chamado do Novo", description: "Este trimestre marca o início de novos movimentos em várias áreas da vida.\n\nO universo coloca à sua frente novos caminhos e oportunidades, convidando você a agir com coragem e propósito.\n\nÉ tempo de liderar, sair da zona de conforto e fazer acontecer.\n\nVocê sentirá um impulso natural para vencer medos e inseguranças. Use essa força para destravar o que estava parado.\n\nA confiança é sua grande aliada agora. Permita-se experimentar, iniciar e aprender com o processo.\n\nSe houver pendências com figuras masculinas (pai, parceiro, chefe, irmão), este é um bom momento para resolver e seguir em frente com leveza." },
  2: { title: "CICLO DO TRIMESTRE 2 – A Força das Parcerias", description: "Com esse trimestre, chega um tempo de equilíbrio e colaboração.\n\nÉ um momento propício para novas parcerias (afetivas, profissionais ou sociais) que podem fortalecer seus projetos e consolidar o que foi ou será iniciado.\n\nA energia pede paciência, escuta e flexibilidade. Aprenda a delegar, confiar e caminhar em conjunto.\n\nÉ um período de aprendizado sobre cooperação e harmonia, onde o 'eu' aprende a coexistir com o 'nós'. Talvez você enxergue uma nova forma de olhar para suas parcerias.\n\nSe o seu trimestre for 11, esta fase desperta a espiritualidade e a intuição. Práticas como meditação, Reiki ou momentos de silêncio interior serão muito benéficas." },
  3: { title: "CICLO DO TRIMESTRE 3 – Criatividade e Expressão", description: "Este trimestre traz inovação, criatividade e expansão.\n\nÉ o momento de colocar ideias em movimento e permitir que a criatividade flua.\n\nSua comunicação estará em alta. Aproveite para se expressar, compartilhar seus projetos e se conectar com novas pessoas.\n\nTudo o que foi iniciado começa a dar os primeiros frutos, por isso direcione sua energia para projetos que gerarão crescimento.\n\nAtividades artísticas, físicas ou de lazer ajudam a equilibrar entusiasmo e ansiedade.\n\nFale, crie, se divirta e se mostre ao mundo com autenticidade e coragem." },
  4: { title: "CICLO DO TRIMESTRE 4 – Estrutura, Disciplina e Construção", description: "Este trimestre pede foco absoluto, disciplina e firmeza interior.\n\nÉ o momento de organizar e estruturar os novos projetos. A energia do 4 exige constância e clareza de metas. Sua força de realização está em alta, e por isso é fundamental manter os pés no chão e acreditar em si. Podem surgir novos projetos ou mudanças no trabalho, pedindo que você assuma uma postura mais segura e madura.\n\nEste é um ciclo de construção sólida, em que o esforço traz resultados concretos e duradouros.\n\nSe o seu trimestre for 22, essa energia também desperta sabedoria espiritual e visão de longo prazo. Use o poder do foco e da fé para equilibrar matéria e alma." },
  5: { title: "CICLO DO TRIMESTRE 5 – Mudanças e Liberdade", description: "Esse trimestre traz movimento, transformação e novas experiências. Esteja aberto e tenha coragem.\n\nQuanto mais autonomia e ousadia, mais oportunidades se manifestam. Independência e liberdade são palavras chave nesse momento. A rotina pode ficar agitada, exigindo jogo de cintura e flexibilidade.\n\nAs mudanças são oportunidades de crescimento, mesmo que tragam desconforto inicial.\n\nAtividades físicas e criativas ajudam a canalizar o excesso de energia e manter o foco." },
  6: { title: "CICLO DO TRIMESTRE 6 – Harmonia e Responsabilidade", description: "Momento de harmonizar e promover conciliação.\n\nA energia pede força, responsabilidade e maturidade emocional, especialmente em assuntos familiares.\n\nPodem surgir inícios no âmbito familiar, como negócios com familiares e/ou amigos, casamentos, filhos ou mudanças no lar.\n\nÉ também um período para se reconectar com a afetividade de forma mais leve e verdadeira, cultivando paz, equilíbrio e amor-próprio.\n\nNo trabalho, lidere com empatia e humanidade. Sua autoridade se fortalece quando vem acompanhada de sensibilidade e respeito" },
  7: { title: "CICLO DO TRIMESTRE 7 – Inícios de Estudo, Autoconhecimento e Espiritualidade", description: "Trimestre propício para inícios ligados ao estudo e autoconhecimento.\n\nLivros, cursos, terapias ou práticas de cura serão grandes aliados no fortalecimento do seu novo ciclo.\n\nO trabalho pode exigir mais eficiência e foco, mas tudo o que você fizer voltado ao seu desenvolvimento interior trará força, clareza e coragem.\n\nVocê pode sentir vontade de se recolher e buscar mais silêncio. Respeite esse movimento.\n\nTambém é um período de inícios espirituais, onde novas conexões e aprendizados podem surgir. Fique atento à sua intuição: ela será o seu melhor guia neste trimestre."},
  8: { title: "CICLO DO TRIMESTRE 8 – Poder e Realização", description: "Este trimestre traz clareza e visão de futuro para os seus projetos.\n\nVocê estará mais racional, focado e determinado. Um ótimo momento para agir com estratégia e ambição.\n\nA energia do 8 amplia seu poder de realização e pode trazer novas oportunidades financeiras ou o início de uma colheita do que foi plantado nos ciclos anteriores.\n\nUse sua força de vontade, organização e praticidade para concretizar metas.\n\nAja sempre com ética e verdade, certificando-se de que suas escolhas estão alinhadas com o que você realmente acredita.\n\nQuando você vive com integridade, o sucesso acontece de forma natural e duradoura." },
  9: { title: "CICLO DO TRIMESTRE 9 – Realização e Abertura para o Novo", description: "Este é um momento de conquistas e concretizações.\n\nVocê colhe os resultados do que vem construindo e percebe seus projetos tomando forma.\n\nA vida pede ação, atitude e confiança. Coloque a mão na massa, acredite em você e exerça sua liderança com coragem.\n\nTambém é um ciclo de desapego e preparação para o novo: finalize o que precisa ser encerrado e abra espaço para o que está por vir.\n\nAcima de tudo, aproveite esta fase de realização e reconhecimento. Desfrute do que conquistou e celebre o caminho percorrido." },
  0: { title: "CICLO DO TRIMESTRE 0 (sem desafio com 0 no mapa) – O Infinito das Possibilidades", description: "Os trimestres 0 são raros e especiais, acontecendo apenas a cada nove anos, no ano do seu desafio.\n\nEles trazem uma energia de expansão e potencial absoluto, em que tudo pode iniciar agora.\n\nO número 0 representa o infinito e amplia as oportunidades em todas as áreas da vida.\n\nDentro do Ano 1, essa vibração favorece novos começos e múltiplos caminhos.\n\nTenha coragem, confie em você e dê o passo com fé. Este é um tempo para se abrir ao novo e permitir que a vida revele suas possibilidades. Uma oportunidade de você vencer medos e inseguranças e dar o passo." },
  '0_with_challenge': { title: "CICLO DO TRIMESTRE 0 (com desafio com 0 no mapa) – Pausa, Reflexão e Reabastecimento de Energia", description: "Evite iniciar projetos, assumir riscos ou entrar em discussões.Aceite as situações como elas se apresentam, sem tentar controlar tudo.\n\nÉ um momento de pausa e reflexão, ideal para ler, meditar, relaxar e cuidar do seu bem-estar.\n\nTA energia vital precisa ser reabastecida, por isso respeite seu ritmo e preserve sua paz.\n\nTudo o que parece parado agora está apenas se reorganizando para o próximo ciclo." },
};

export default quarterCycleTexts;
