export const soulNumberInterpretations: {
  [key: number]: { title: string; description: string }
} = {
  0: { title: "Alma", description: "A sua alma carrega uma energia especial e única, com características próprias que se manifestam de forma singular na sua jornada de vida." },
  1: { title: "Alma", description: "A sua alma é autêntica, independente e livre. O que mais te motiva é seguir o seu próprio caminho e conquistar autonomia, sem se submeter a limitações ou dependências. Você vibra quando tem liberdade para decidir e ousar, quando sente que pode confiar no seu instinto e dar o primeiro passo. Essa essência carrega uma grande necessidade de autoafirmação: você precisa se sentir forte, capaz e realizado pelas suas próprias conquistas. No fundo, a sua verdade é clara: você nasceu para acreditar em si mesmo. Sua alma se expande quando você confia na sua voz interior e reconhece que tem dentro de si a força necessária para vencer qualquer desafio." },
  2: { title: "Alma", description: "A sua alma é gentil, paciente e generosa. O que mais te motiva é sentir-se próximo das pessoas, compartilhar a vida e se dedicar a quem ama. Você vibra quando pode cuidar, apoiar e oferecer presença, porque dentro de você existe uma necessidade genuína de ser útil e de estar ao lado dos outros. Sua essência é colaborativa: você se realiza em ambientes de grupo, onde pode exercer sua escuta atenta, sua cordialidade e seu espírito de parceria." },
  3: { title: "Alma", description: "A sua alma é comunicativa, expansiva e criativa. O que mais te motiva é ter liberdade para expressar quem você é, seja falando, escrevendo, cantando, pintando ou simplesmente compartilhando sua alegria com quem está ao seu lado. Você vibra quando pode se movimentar, se divertir e criar conexões leves com as pessoas. Sua essência é otimista: você nasceu para trazer brilho e inspiração, para lembrar que a vida pode ser vivida com simplicidade e alegria." },
  4: { title: "Alma", description: "A sua alma busca disciplina, equilíbrio e segurança, mas acima de tudo precisa se sentir produtiva. O que mais te motiva é perceber que está construindo algo, que está construindo e fazendo a diferença. Você vibra quando consegue manter uma rotina organizada, quando cumpre suas responsabilidades e vê o resultado concreto do seu esforço. Para você, a vida profissional é muito importante e através dela que contraparte da sua realização pessoal. Você sente que sua essência valoriza o compromisso, a lealdade e a constância. No fundo, sua alma tem uma base firme, equilibrada e segura." },
  5: { title: "Alma", description: "A sua alma é livre, curiosa e aventureira. O que mais te motiva é sentir-se em movimento, descobrindo coisas novas, seja em uma viagem, em uma prática esportiva, em um contato com a natureza ou em experiências que despertem sua vitalidade. Você vibra quando pode explorar, mudar e se reinventar. Sua essência pede intensidade e prazer, mas também diversidade: você não nasceu para viver no mesmo lugar ou na mesma rotina por muito tempo. Sua alma encontra realização quando se sente independente, conectado ao mundo e capaz de experimentar a vida em todas as suas cores." },
  6: { title: "Alma", description: "A sua alma é amorosa, sensível e profundamente responsável. O que mais te motiva é sentir-se parte de um círculo íntimo, onde possa oferecer cuidado, apoio e equilíbrio. Você vibra quando está próximo de quem ama, quando pode ser um ponto de estabilidade e transmitir confiança. Sua essência é marcada pela emotividade e pela responsabilidade: você sente profundamente e assume compromissos de forma séria e dedicada. A alma 6 se realiza ao cuidar da família de origem, da família que constrói ao longo da vida e também dos amigos que são parte da sua história." },
  7: { title: "Alma", description: "A sua alma é profunda, intuitiva e em constante busca. O que mais te motiva é compreender o sentido da vida e mergulhar em práticas de autoconhecimento que tragam clareza e evolução. Você vibra quando sente que está aprendendo, investigando e se aprofundando em silêncio. Sua essência é reservada e sensível: você não se satisfaz com o superficial, busca a verdade em tudo o que faz e valoriza autenticidade e profundidade. No fundo, sua alma encontra paz quando consegue confiar na própria intuição, equilibrando sabedoria intelectual e sabedoria espiritual." },
  8: { title: "Alma", description: "A sua alma é forte, determinada e ética. O que mais te motiva é viver com transparência, ser reconhecido pelo que faz e sentir que está no caminho da retidão. Você vibra quando conquista algo com seu esforço, quando é valorizado pelo que entrega e quando sente que está prosperando de forma justa. Sua essência também aprecia a sofisticação e as coisas boas da vida, porque você associa prosperidade com bem-estar e qualidade. No fundo, sua alma se realiza quando consegue unir conquistas materiais com verdade, propósito e ética." },
  9: { title: "Alma", description: "A sua alma é puro amor universal. O que mais te motiva é cuidar, acolher e servir sem esperar nada em troca. Você se sente realizado quando pode contribuir para o bem-estar das pessoas ao seu redor. Tem grande sensibilidade e intuição, captando facilmente dores e alegrias, e por isso busca constantemente trazer harmonia aos relacionamentos. Sua essência é compassiva e acolhedora, mas também precisa aprender que, assim como doa amor, também merece recebê-lo." },
  11: { title: "Alma", description: "A sua alma é profundamente espiritual e ao mesmo tempo humana e acolhedora. O que mais te motiva é sentir-se conectado a algo maior e, ao mesmo tempo, partilhar essa conexão com as pessoas que ama. Você vibra quando pode apoiar, compartilhar e estar em união, porque dentro de você existe a força do 2, a generosidade, a parceria, a escuta,  junto da luz do 11/2 a intuição, a cura e a conexão espiritual. Sua alma precisa de silêncio e espiritualidade para se reabastecer, mas também precisa da presença do outro para se sentir plena. No fundo, sua alma se realiza quando consegue servir, amar e estar em equilíbrio entre a fé e os vínculos humanos." },
  22: { title: "Alma", description: "A sua alma é grandiosa, espiritual e prática ao mesmo tempo. O que mais te motiva é sentir que tem uma missão maior, que está aqui para ensinar, guiar e transformar vidas através do que constrói. Você vibra quando consegue unir a espiritualidade com a prática, quando vê que a sua visão pode se concretizar e impactar muitas pessoas. A alma 22/4 tem sensibilidade mágica, sente a força da natureza, percebe sutilezas energéticas e tem facilidade em captar sinais do invisível. Mas também precisa da rotina, do trabalho e da disciplina do 4 para se sentir realizada. No fundo, sua alma encontra paz quando consegue viver sua mestria: ser canal de conhecimento, de espiritualidade e de realização concreta." }

};
