export const talentNumberInterpretations: {
  [key: number]: { title: string; description: string }
} = {
   0: { title: "Talento", description: "O seu talento carrega uma energia especial e única, com habilidades próprias que se manifestam de forma singular na sua expressão pessoal." },
  1: { title: "Talento", description: "O seu talento está na iniciativa, na coragem e na determinação. Você é percebido como alguém confiante, forte e capaz de liderar, mesmo quando não se sente assim por dentro. Seu dom natural é a força de decisão: quando você escolhe algo, vai até o fim, mostrando disciplina e persistência. Esse talento faz de você um excelente líder, empreendedor ou criador, alguém que consegue enxergar além e dar o primeiro passo onde outros hesitam. Você atrai oportunidades justamente porque é visto como pioneiro e inovador, alguém que traz soluções novas e inspira movimento. Seu talento é iluminar caminhos, mostrando que com confiança e ação é possível realizar qualquer coisa." },
  2: { title: "Talento", description: "O seu talento está na escuta, na cordialidade e na diplomacia. Você tem um dom natural para perceber os sentimentos das pessoas e encontrar formas de trazer entendimento e conexão nos relacionamentos. Sua presença transmite cuidado e acolhimento, e por isso as pessoas se sentem à vontade ao seu lado. Você sabe como criar um clima de respeito e de cooperação, e esse é o seu diferencial: unir, integrar e suavizar os ambientes, trazendo flexibilidade e generosidade para cada situação." },
  3: { title: "Talento", description: "O seu talento está na comunicação e na criatividade. Você tem o dom de se expressar de forma natural, encantando e cativando quem está ao seu redor. Sua capacidade de falar, escrever ou simplesmente transmitir energia positiva é um presente que atrai pessoas e oportunidades. Você também tem talento para se adaptar, improvisar e encontrar soluções criativas em situações inesperadas. Sua presença é vista como leve, animada e contagiante — e esse é o seu diferencial: estimular ambientes e pessoas com a sua espontaneidade e alegria de viver." },
  4: { title: "Talento", description: "O seu talento está na disciplina, na persistência e na capacidade de organizar. Você tem o dom de ser detalhista e focado, e consegue realizar tarefas que exigem constância e comprometimento. Sua força é transformar ideias em realidade por meio de planejamento e execução. Você se sente vivo quando está produzindo, entregando e vendo os frutos do seu esforço no mundo. As pessoas te enxergam como alguém confiável, profissional e comprometido, capaz de criar ordem onde há caos. Esse é o seu diferencial: transformar esforço contínuo em resultados concretos e duradouros." },
  5: { title: "Talento", description: "O seu talento está na versatilidade, na comunicação e na capacidade de se adaptar a qualquer situação. Você tem o dom de se reinventar, de se abrir para o novo e de viver a vida com espontaneidade. Sua energia é contagiante: você movimenta ambientes, traz novidades e inspira coragem nos outros. O contato com o mundo, com a natureza e com tudo que envolve vitalidade desperta ainda mais o seu brilho. Você também tem talento para explorar caminhos que ninguém ousou, assumindo riscos e mostrando que é possível viver com liberdade e leveza. Esse é o seu diferencial: transformar movimento em aprendizado, aventuras em sabedoria e vitalidade em inspiração." },
  6: { title: "Talento", description: "O seu talento está no cuidado, no zelo e na responsabilidade com aquilo que assume. Você tem o dom de pacificar, de unir pessoas e de trazer harmonia para os ambientes. Sua presença transmite confiança, afeto e lealdade, e faz com que os outros sintam segurança ao seu lado. Você também tem talento para cultivar amizades duradouras, valorizar a família e ser referência de amor e compromisso. Esse é o seu diferencial: a habilidade de cuidar, de proteger e de assumir responsabilidades de forma madura, mostrando que o amor e a harmonia são as maiores forças que existem." },
  7: { title: "Talento", description: "O seu talento está na análise, na curiosidade e na capacidade de enxergar além. Você tem o dom de investigar, de perceber detalhes que passam despercebidos para os outros e de mergulhar em estudos profundos. Seu talento floresce quando você une disciplina com intuição, transformando o conhecimento em sabedoria prática. Você é naturalmente visto como alguém detalhista, exigente e confiável, justamente porque transmite a seriedade de quem busca compreender a fundo. O seu diferencial é viver o autoconhecimento como ferramenta essencial e inspirar outras pessoas a também mergulharem em sua própria jornada interior." },
  8: { title: "Talento", description: "O seu talento está na justiça, na objetividade e na transparência. Você tem o dom de administrar recursos, planejar com clareza e transformar sua visão em resultados concretos. As pessoas confiam em você porque percebem sua honestidade e integridade, enxergam sua seriedade e reconhecem sua confiabilidade. Sua força está na clareza de análise e na firmeza das decisões, sempre buscando excelência em tudo o que faz. Você também tem talento para prosperar financeiramente, conquistar posições de destaque e organizar caminhos que levem ao crescimento. O seu diferencial é unir ambição e sofisticação com ética e retidão, mostrando que é possível prosperar sem perder os princípios." },
  9: { title: "Talento", description: "O seu talento está na empatia, no acolhimento e na espiritualidade. Você tem o dom de sentir profundamente o outro e de oferecer apoio de forma genuína, transmitindo amor e generosidade. O 9 no talento mostra que você pode inspirar e ajudar as pessoas de muitas formas. Através de palavras, gestos, presença ou ações ligadas à arte, à espiritualidade ou às causas sociais. As pessoas te veem como alguém iluminado, capaz de levar amor, acolhimento e esperança para quem precisa. O seu diferencial é a capacidade de se conectar com a dor e a alegria do outro, ajudando a transformar sofrimento em amor e fé." },
  11: { title: "Talento", description: "O seu talento está na intuição e na empatia, mas também na capacidade de criar união e harmonia ao seu redor. O 11/2 no talento mostra que você tem dons espirituais, sensibilidade e poder de cura, mas também traz a delicadeza do 2: generosidade, diplomacia, escuta e parceria. Você é alguém que transmite confiança e paz, que sabe acolher e apoiar, e por isso as pessoas se sentem seguras ao seu lado. O seu diferencial é unir o dom espiritual do 11/2 com a ternura humana do 2, iluminando pela sua sensibilidade e acolhendo pela sua presença." },
  22: { title: "Talento", description: "O seu talento está na genialidade, na visão e na capacidade de transformar o impossível em possível. Você tem o dom de planejar, construir e realizar em grande escala, mas também a sensibilidade espiritual para guiar pessoas, ensinar e transmitir conhecimento. O 22/4 no talento mostra que você pode unir prática e magia, disciplina e espiritualidade, criando projetos ou ensinamentos que transformam vidas. Sua força está em perceber o todo, captar as energias sutis e, ao mesmo tempo, organizar os detalhes para que tudo se concretize. O seu diferencial é ser um mestre visionário: alguém que inspira, ensina e constrói, deixando marcas profundas tanto no plano material quanto no espiritual." }

};
