export const getMonthlyGuidance = (month: number, year: number): string => {
  const guidance: { [key: string]: string } = {
    '1-1': 'Mês perfeito para iniciar projetos. Sua energia está no auge!',
    '1-2': 'Foque em parcerias que apoiem seus novos começos.',
    '1-3': 'Comunique suas ideias com clareza e confiança.',
    '1-4': 'Organize os detalhes dos projetos iniciados.',
    '1-5': 'Esteja aberto a ajustes e mudanças de rota.',
    '1-6': 'Equilibre ambição profissional com vida familiar.',
    '1-7': 'Reflita sobre o progresso e ajuste estratégias.',
    '1-8': 'Mês favorável para questões financeiras.',
    '1-9': 'Finalize o que não serve mais antes do novo ciclo.',
    '1-10': 'Celebre conquistas e planeje próximos passos.',
    '1-11': 'Intuição elevada - confie nos insights.',
    '1-12': 'Encerre o ano com gratidão e preparação.',
    '2-1': 'Inicie o ano fortalecendo vínculos importantes.',
    '2-2': 'Mês de alta sensibilidade - pratique autocuidado.',
    '2-3': 'Comunique sentimentos com clareza e amor.',
    '2-4': 'Construa bases sólidas nos relacionamentos.',
    '2-5': 'Aceite mudanças nas dinâmicas relacionais.',
    '2-6': 'Harmonia familiar em destaque - cuide do lar.',
    '2-7': 'Momento de introspecção sobre parcerias.',
    '2-8': 'Acordos e contratos favorecem prosperidade.',
    '2-9': 'Libere relações que não nutrem mais.',
    '2-10': 'Celebre conexões verdadeiras.',
    '2-11': 'Intuição guia decisões relacionais.',
    '2-12': 'Gratidão pelas pessoas que apoiaram você.',
    '3-1': 'Comunique suas ideias com entusiasmo!',
    '3-2': 'Colaborações criativas trazem resultados.',
    '3-3': 'Mês de máxima expressão e criatividade.',
    '3-4': 'Organize projetos criativos com disciplina.',
    '3-5': 'Explore novas formas de se expressar.',
    '3-6': 'Compartilhe talentos com família e comunidade.',
    '3-7': 'Aprofunde conhecimentos em áreas de interesse.',
    '3-8': 'Monetize seus talentos criativos.',
    '3-9': 'Finalize projetos antes de iniciar novos.',
    '3-10': 'Celebre conquistas criativas.',
    '3-11': 'Inspiração elevada - capture ideias.',
    '3-12': 'Planeje expansão criativa para próximo ano.',
    '4-1': 'Estabeleça metas claras e planos de ação.',
    '4-2': 'Trabalhe em equipe com disciplina.',
    '4-3': 'Comunique planos e organize detalhes.',
    '4-4': 'Mês de trabalho intenso - foque na construção.',
    '4-5': 'Adapte estruturas quando necessário.',
    '4-6': 'Organize lar e rotinas familiares.',
    '4-7': 'Revise processos e otimize sistemas.',
    '4-8': 'Colha frutos do trabalho árduo.',
    '4-9': 'Finalize projetos e organize pendências.',
    '4-10': 'Celebre bases sólidas construídas.',
    '4-11': 'Intuição sobre próximos passos práticos.',
    '4-12': 'Planeje estrutura para o novo ano.',
    '5-1': 'Ano de mudanças começa - abrace o novo!',
    '5-2': 'Parcerias trazem oportunidades inesperadas.',
    '5-3': 'Comunique desejo de liberdade com clareza.',
    '5-4': 'Organize mudanças com planejamento.',
    '5-5': 'Mês de máxima liberdade - explore possibilidades!',
    '5-6': 'Equilibre aventura com responsabilidades.',
    '5-7': 'Reflita sobre mudanças antes de agir.',
    '5-8': 'Mudanças financeiras positivas no horizonte.',
    '5-9': 'Libere o antigo para abraçar o novo.',
    '5-10': 'Celebre coragem de mudar.',
    '5-11': 'Intuição guia para próximas aventuras.',
    '5-12': 'Planeje viagens e expansões futuras.',
    '6-1': 'Assuma responsabilidades com amor.',
    '6-2': 'Fortaleça laços familiares e parcerias.',
    '6-3': 'Expresse amor e cuidado abertamente.',
    '6-4': 'Construa estabilidade no lar.',
    '6-5': 'Adapte-se a mudanças familiares.',
    '6-6': 'Mês de máxima harmonia - cuide de todos.',
    '6-7': 'Reflita sobre propósito de servir.',
    '6-8': 'Invista em conforto e bem-estar familiar.',
    '6-9': 'Libere obrigações que pesam demais.',
    '6-10': 'Celebre amor e união familiar.',
    '6-11': 'Intuição sobre necessidades dos outros.',
    '6-12': 'Gratidão pelo lar e família.',
    '7-1': 'Inicie ano com introspecção profunda.',
    '7-2': 'Busque parcerias espirituais.',
    '7-3': 'Comunique sabedoria adquirida.',
    '7-4': 'Estruture práticas espirituais.',
    '7-5': 'Explore novos caminhos de conhecimento.',
    '7-6': 'Equilibre solidão com responsabilidades.',
    '7-7': 'Mês de máxima conexão espiritual.',
    '7-8': 'Invista em educação e crescimento.',
    '7-9': 'Libere crenças limitantes.',
    '7-10': 'Celebre sabedoria conquistada.',
    '7-11': 'Intuição no auge - medite e ouça.',
    '7-12': 'Planeje jornada espiritual futura.',
    '8-1': 'Estabeleça metas ambiciosas de sucesso.',
    '8-2': 'Parcerias estratégicas trazem poder.',
    '8-3': 'Comunique autoridade com confiança.',
    '8-4': 'Construa império com trabalho sólido.',
    '8-5': 'Adapte estratégias para maximizar ganhos.',
    '8-6': 'Equilibre sucesso com vida familiar.',
    '8-7': 'Reflita sobre uso do poder.',
    '8-8': 'Mês de máxima abundância e realização!',
    '8-9': 'Finalize negócios e colha recompensas.',
    '8-10': 'Celebre conquistas materiais.',
    '8-11': 'Intuição sobre investimentos futuros.',
    '8-12': 'Planeje expansão financeira.',
    '9-1': 'Inicie encerramento de ciclos com sabedoria.',
    '9-2': 'Libere parcerias que completaram propósito.',
    '9-3': 'Comunique fechamentos com compaixão.',
    '9-4': 'Organize e finalize projetos pendentes.',
    '9-5': 'Aceite mudanças como parte do fim.',
    '9-6': 'Perdoe e libere com amor.',
    '9-7': 'Reflita sobre lições do ciclo completo.',
    '9-8': 'Resolva questões financeiras pendentes.',
    '9-9': 'Mês de conclusão total - libere tudo!',
    '9-10': 'Celebre fim de ciclo com gratidão.',
    '9-11': 'Intuição sobre próximo grande ciclo.',
    '9-12': 'Prepare-se para renascimento no Ano 1.'
  };
  return guidance[`${year}-${month}`] || 'Mês de crescimento.';
};
